// <auto-generated/>
// DO NOT EDIT: このファイルは master-data-pipeline によって自動生成されています。
// 直接編集せず、スプレッドシートまたは schema/ 配下の定義を変更してください。
namespace Atlas.MasterData.Models
{
    using MasterMemory;
    using MessagePack;
    using Atlas.MasterData.Enums;

    [MemoryTable("items")]
    [MessagePackObject(true)]
    public partial class ItemsData
    {
        [PrimaryKey]
        public int ItemId { get; set; }
        public string Name { get; set; }
    }
}
