// <auto-generated/>
// DO NOT EDIT: このファイルは master-data-pipeline によって自動生成されています。
// 直接編集せず、スプレッドシートまたは schema/ 配下の定義を変更してください。
namespace Atlas.MasterData.Models
{
    using MasterMemory;
    using MessagePack;
    using Atlas.MasterData.Enums;

    [MemoryTable("pachimon")]
    [MessagePackObject(true)]
    public partial class PachimonData
    {
        [PrimaryKey]
        public int PachimonId { get; set; }
        public string Name { get; set; }
        public PachimonType PrimaryType { get; set; }
        public PachimonType SecondaryType { get; set; }
        public int BaseHp { get; set; }
        public int BaseAtk { get; set; }
        public int BaseDef { get; set; }
        public int BaseSpatk { get; set; }
        public int BaseSpdef { get; set; }
        public int BaseSpeed { get; set; }
        public Rarity Rarity { get; set; }
        public int MoveGroupId { get; set; }
    }
}
