// <auto-generated/>
// DO NOT EDIT: このファイルは master-data-pipeline によって自動生成されています。
// 直接編集せず、スプレッドシートまたは schema/ 配下の定義を変更してください。
namespace Atlas.MasterData.Models
{
    using MasterMemory;
    using MessagePack;
    using Atlas.MasterData.Enums;

    [MemoryTable("type_chart")]
    [MessagePackObject(true)]
    public partial class TypeChartData
    {
        [PrimaryKey]
        public int TypeChartId { get; set; }
        public PachimonType AttackType { get; set; }
        public PachimonType DefendType { get; set; }
        public TypeEffectiveness Effectiveness { get; set; }
    }
}
