// <auto-generated/>
// DO NOT EDIT: このファイルは master-data-pipeline によって自動生成されています。
// 直接編集せず、スプレッドシートまたは schema/ 配下の定義を変更してください。
namespace YourGame.Domain.MasterData.Enums
{
    public enum Rarity
    {
        S = 1,
        A = 2,
        B = 3,
        C = 4
    }
}
