// <auto-generated/>
// DO NOT EDIT: このファイルは api-codegen によって自動生成されています。
// 直接編集せず、入力元のOpenAPI仕様書(サーバー側のhandler定義)を変更してください。
using System;
using Atlas.Infrastructure.Api.Dto;
using Cysharp.Threading.Tasks;

namespace Atlas.Infrastructure.Api.Client
{
    public sealed class ChatApiClient
    {
        private readonly string _baseUrl;
        private readonly Func<string> _accessTokenProvider;

        public ChatApiClient(string baseUrl, Func<string> accessTokenProvider)
        {
            _baseUrl = baseUrl;
            _accessTokenProvider = accessTokenProvider;
        }

        public UniTask<PollMessagesResponse> PollMessagesAsync()
            => ApiRequest.SendAsync<PollMessagesResponse>(_baseUrl, "GET", "/chat/poll", null, _accessTokenProvider());

        public UniTask<SendMessageResponse> SendMessageAsync(SendMessageRequest request)
            => ApiRequest.SendAsync<SendMessageResponse>(_baseUrl, "POST", "/chat/send", request, _accessTokenProvider());
    }
}
