// <auto-generated/>
// DO NOT EDIT: このファイルは api-codegen によって自動生成されています。
// 直接編集せず、入力元のOpenAPI仕様書(サーバー側のhandler定義)を変更してください。
using System;
using Atlas.Infrastructure.Api.Dto;
using Cysharp.Threading.Tasks;

namespace Atlas.Infrastructure.Api.Client
{
    public sealed class DeviceApiClient
    {
        private readonly string _baseUrl;

        public DeviceApiClient(string baseUrl)
        {
            _baseUrl = baseUrl;
        }

        public UniTask<RegisterDeviceResponse> RegisterDeviceAsync(RegisterDeviceRequest request)
            => ApiRequest.SendAsync<RegisterDeviceResponse>(_baseUrl, "POST", "/devices", request, null);

        public UniTask<AuthenticateDeviceResponse> AuthenticateDeviceAsync(AuthenticateDeviceRequest request)
            => ApiRequest.SendAsync<AuthenticateDeviceResponse>(_baseUrl, "POST", "/devices/authenticate", request, null);
    }
}
