// <auto-generated/>
// DO NOT EDIT: このファイルは api-codegen によって自動生成されています。
// 直接編集せず、入力元のOpenAPI仕様書(サーバー側のhandler定義)を変更してください。
using System;
using Atlas.Infrastructure.Api.Dto;
using Cysharp.Threading.Tasks;

namespace Atlas.Infrastructure.Api.Client
{
    public sealed class ScoutApiClient
    {
        private readonly string _baseUrl;
        private readonly Func<string> _accessTokenProvider;

        public ScoutApiClient(string baseUrl, Func<string> accessTokenProvider)
        {
            _baseUrl = baseUrl;
            _accessTokenProvider = accessTokenProvider;
        }

        public UniTask<ListBannersResponse> ListBannersAsync()
            => ApiRequest.SendAsync<ListBannersResponse>(_baseUrl, "GET", "/scout/banners", null, _accessTokenProvider());

        public UniTask<CreateRollResponse> CreateRollAsync(CreateRollRequest request)
            => ApiRequest.SendAsync<CreateRollResponse>(_baseUrl, "POST", "/scout/rolls", request, _accessTokenProvider());

        public UniTask<SelectRollResponse> SelectRollAsync(string rollId, SelectRollRequest request)
            => ApiRequest.SendAsync<SelectRollResponse>(_baseUrl, "POST", $"/scout/rolls/{rollId}/select", request, _accessTokenProvider());
    }
}
