//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Application.Address
{
    
    public partial class AddressDefinition
    {
        public const string masterdata = "masterdata";
        public const string Battle = "Battle";
        public const string BattlePage = "BattlePage";
        public const string BattleResultModal = "BattleResultModal";
        public const string CommandCanvas = "CommandCanvas";
        public const string ForfeitConfirmModal = "ForfeitConfirmModal";
        public const string Home = "Home";
        public const string HomePage = "HomePage";
        public const string MatchmakingModal = "MatchmakingModal";
        public const string OpponentCanvas = "OpponentCanvas";
        public const string OpponentSwitchingModal = "OpponentSwitchingModal";
        public const string PartyStatRow1prefab = "Party/StatRow1.prefab";
        public const string PartyPage = "PartyPage";
        public const string ScoutConfirmModal = "ScoutConfirmModal";
        public const string ScoutPage = "ScoutPage";
        public const string SelfCanvas = "SelfCanvas";
        public const string SwitchSelectModal = "SwitchSelectModal";
        public const string TitlePage = "TitlePage";
        public const string ViewsPartsCellTemplateprefab = "Views/Parts/CellTemplate.prefab";
        public const string ViewsPartsPachimonInfoPanelprefab = "Views/Parts/PachimonInfoPanel.prefab";
        public const string white_2x2 = "white_2x2";
    }
}
