//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Addressables
{
    
    public partial class AddressDefinition
    {
        public partial class Battle
        {
        }
        public partial class MasterData
        {
            public const string AssetsAddressablesMasterDatamasterdatabytes = "Assets/Addressables/MasterData/masterdata.bytes";
        }
        public partial class DefaultLocalGroup
        {
            public const string Home = "Home";
            public const string HomePage = "HomePage";
            public const string TitlePage = "TitlePage";
        }
    }
}
