// <auto-generated/>
// DO NOT EDIT: このファイルは api-codegen によって自動生成されています。
// 直接編集せず、入力元のOpenAPI仕様書(サーバー側のhandler定義)を変更してください。
namespace Atlas.Infrastructure.Api.Dto
{
    using System.Text.Json.Serialization;

    public sealed class CreateRollResponse
    {
        [JsonPropertyName("candidates")]
        public System.Collections.Generic.List<CandidateDto> Candidates { get; set; }

        [JsonPropertyName("gems")]
        public int Gems { get; set; }

        [JsonPropertyName("rollId")]
        public string RollId { get; set; }
    }
}
