// <auto-generated/>
// DO NOT EDIT: このファイルは api-codegen によって自動生成されています。
// 直接編集せず、入力元のOpenAPI仕様書(サーバー側のhandler定義)を変更してください。
namespace Atlas.Infrastructure.Api.Dto
{
    using System.Text.Json.Serialization;

    public sealed class PlayerResponse
    {
        [JsonPropertyName("gems")]
        public int Gems { get; set; }

        [JsonPropertyName("nickname")]
        public string Nickname { get; set; }

        [JsonPropertyName("playerId")]
        public string PlayerId { get; set; }
    }
}
