// <auto-generated/>
// DO NOT EDIT: このファイルは master-data-pipeline によって自動生成されています。
// 直接編集せず、スプレッドシートまたは schema/ 配下の定義を変更してください。
using MasterMemory;
using MessagePack;
using MessagePack.Resolvers;

namespace Atlas.MasterData
{
    /// <summary>
    /// masterdata.bytes の復号 + MemoryDatabase構築ロジック。
    /// Unity(クライアント)・MagicOnion(リアルタイムサーバー)の両方に同一の
    /// ファイルとしてコピーされる(bytesの取得方法だけが環境ごとに異なる)。
    /// </summary>
    public static class MasterDataLoader
    {
        /// <summary>
        /// schema/tables, schema/enums の内容から算出したcontent_hash。
        /// 復号パスワードとして使う。スキーマが変わるとこの値も変わり、
        /// 古い masterdata.bytes は復号できなくなる(想定どおりの挙動)。
        /// </summary>
        public const string ContentHash = "4d3cf8fb3b961cce8b815a4a0823a8643f094b0bb6ffb85072143df3f5ece522";

        // MasterMemoryResolver / MemoryDatabase はこのプロジェクトのビルド時に
        // MasterMemory.SourceGenerator が生成する(同一名前空間に存在する前提)。
        // StandardResolverはMessagePackのSource Generator出力を内部で
        // 自動的に含むため、POCO([MessagePackObject])用のResolverを
        // 個別に参照する必要はない。
        private static readonly IFormatterResolver Resolver =
            CompositeResolver.Create(
                MasterMemoryResolver.Instance,
                StandardResolver.Instance);

        public static MemoryDatabase Load(byte[] encryptedBytes)
        {
            var decrypted = AesCrypto.Decrypt(encryptedBytes, ContentHash);
            return new MemoryDatabase(decrypted, formatterResolver: Resolver);
        }
    }
}