// <auto-generated/>
// DO NOT EDIT: このファイルは master-data-pipeline によって自動生成されています。
// 直接編集せず、スプレッドシートまたは schema/ 配下の定義を変更してください。
namespace Atlas.MasterData.Enums
{
    public enum MoveCategory
    {
        Physical = 1,
        Special = 2,
        Status = 3
    }
}
