// <auto-generated/>
// DO NOT EDIT: このファイルは master-data-pipeline によって自動生成されています。
// 直接編集せず、スプレッドシートまたは schema/ 配下の定義を変更してください。
namespace YourGame.Domain.MasterData.Models
{
    using MasterMemory;
    using MessagePack;
    using YourGame.Domain.MasterData.Enums;

    [MemoryTable("move_group_master")]
    [MessagePackObject(true)]
    public class MoveGroupMaster
    {
        [PrimaryKey]
        public int UniqueId { get; set; }
        public int GroupId { get; set; }
        public int MoveId { get; set; }
        public bool IsInitial { get; set; }
    }
}
