// <auto-generated/>
// DO NOT EDIT: このファイルは master-data-pipeline によって自動生成されています。
// 直接編集せず、スプレッドシートまたは schema/ 配下の定義を変更してください。
namespace YourGame.Domain.MasterData.Models
{
    using MasterMemory;
    using MessagePack;
    using YourGame.Domain.MasterData.Enums;

    [MemoryTable("moves")]
    [MessagePackObject(true)]
    public class Moves
    {
        [PrimaryKey]
        public int MoveId { get; set; }
        public string Name { get; set; }
        public PachimonType MoveType { get; set; }
        public MoveCategory Category { get; set; }
        public int BasePower { get; set; }
        public int Accuracy { get; set; }
        public int MaxPp { get; set; }
    }
}
