// <auto-generated/>
// DO NOT EDIT: このファイルは master-data-pipeline によって自動生成されています。
// 直接編集せず、スプレッドシートまたは schema/ 配下の定義を変更してください。
namespace YourGame.Domain.MasterData.Models
{
    using MasterMemory;
    using MessagePack;
    using YourGame.Domain.MasterData.Enums;

    [MemoryTable("move_groups")]
    [MessagePackObject(true)]
    public class MoveGroups
    {
        [PrimaryKey]
        public int MoveGroupId { get; set; }
        public string Name { get; set; }
    }
}
