// <auto-generated/>
// DO NOT EDIT: このファイルは master-data-pipeline によって自動生成されています。
// 直接編集せず、スプレッドシートまたは schema/ 配下の定義を変更してください。
namespace Atlas.MasterData.Enums
{
    public enum TypeEffectiveness
    {
        Immune = 1,
        NotVeryEffective = 2,
        Normal = 3,
        SuperEffective = 4
    }
}
