// <auto-generated/>
// DO NOT EDIT: このファイルは master-data-pipeline によって自動生成されています。
// 直接編集せず、スプレッドシートまたは schema/ 配下の定義を変更してください。
using System;
using System.Security.Cryptography;

namespace Atlas.MasterData
{
    public static class AesCrypto
    {
        // フォーマット: [ Salt(16) | IV(16) | Cipher ]
        private const int KeySizeInBytes = 16; // AES-128
        private const int SaltSizeInBytes = 16;
        private const int Pbkdf2IterationCount = 1000;
        private static readonly HashAlgorithmName Pbkdf2HashAlgorithm = HashAlgorithmName.SHA256;

        public static byte[] Encrypt(byte[] plainData, string password)
        {
            var salt = new byte[SaltSizeInBytes];
            RandomNumberGenerator.Fill(salt);

            using var aes = Aes.Create();
            aes.Mode = CipherMode.CBC;
            aes.Padding = PaddingMode.PKCS7;
            aes.Key = DeriveKey(password, salt);
            aes.GenerateIV();

            using var encryptor = aes.CreateEncryptor();
            var cipherText = encryptor.TransformFinalBlock(plainData, 0, plainData.Length);

            var result = new byte[SaltSizeInBytes + aes.IV.Length + cipherText.Length];
            Buffer.BlockCopy(salt, 0, result, 0, SaltSizeInBytes);
            Buffer.BlockCopy(aes.IV, 0, result, SaltSizeInBytes, aes.IV.Length);
            Buffer.BlockCopy(cipherText, 0, result, SaltSizeInBytes + aes.IV.Length, cipherText.Length);
            return result;
        }

        public static byte[] Decrypt(byte[] encryptedData, string password)
        {
            using var aes = Aes.Create();
            aes.Mode = CipherMode.CBC;
            aes.Padding = PaddingMode.PKCS7;

            var salt = new byte[SaltSizeInBytes];
            Buffer.BlockCopy(encryptedData, 0, salt, 0, SaltSizeInBytes);

            var iv = new byte[aes.IV.Length];
            Buffer.BlockCopy(encryptedData, SaltSizeInBytes, iv, 0, iv.Length);
            aes.IV = iv;

            aes.Key = DeriveKey(password, salt);

            var cipherOffset = SaltSizeInBytes + iv.Length;
            var cipherLength = encryptedData.Length - cipherOffset;
            var cipherText = new byte[cipherLength];
            Buffer.BlockCopy(encryptedData, cipherOffset, cipherText, 0, cipherLength);

            using var decryptor = aes.CreateDecryptor();
            return decryptor.TransformFinalBlock(cipherText, 0, cipherText.Length);
        }

        private static byte[] DeriveKey(string password, byte[] salt)
        {
            using var deriveBytes = new Rfc2898DeriveBytes(password, salt, Pbkdf2IterationCount, Pbkdf2HashAlgorithm);
            return deriveBytes.GetBytes(KeySizeInBytes);
        }
    }
}